# Generated by Django 4.2.24 on 2025-09-21 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='valid_booking_dates',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='listings_re_reviewe_967693_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('private_room', 'Private Room'), ('villa', 'Villa'), ('cottage', 'Cottage')], default='apartment', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='valid_dates'),
        ),
    ]
