#!/bin/bash
# Blue-Green Deployment Automation Script

# Deploy both versions
kubectl apply -f messaging_app/blue_deployment.yaml
kubectl apply -f messaging_app/green_deployment.yaml
kubectl apply -f messaging_app/kubeservice.yaml

echo "Current version of service:"
kubectl get service django-service -o=jsonpath='{.spec.selector.version}'; echo

# Switch traffic from blue → green
kubectl patch service django-service -p '{"spec":{"selector":{"app":"django","version":"green"}}}'

echo "Switched traffic to GREEN version."

# Verify which pods are running
kubectl get pods -l app=django
